# Generated by Django 4.1.5 on 2023-01-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalLittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='features',
            new_name='featured',
        ),
    ]
