# Generated by Django 4.1.4 on 2023-01-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='LittleLemon_price_e9107e_idx',
        ),
    ]
